### ISSUE TITLE
Местоимения

### ISSUE THREAD

**Issue by cheshiren** [yandexx/RInform#2]
В Russian.h местоимения описаны через массив LanguagePronouns.
Но местоимений явно не хватает, есть только «его», «него», «ее», «нее», «их», «них». Также в комментариях к этому массиву написано: «NB: прочие падежи???» Почему-то автор не прописал остальные падежные формы местоимений.

**Comment by fireton** [comment]
А оно надо? Возможно, для сообщений хватает и того.

**Comment by yandexx** [comment]
Для сообщений хватает, но для ввода -- нет, например, "ему" или "ей" (ОСМ КОЛДУНА. ДАТЬ ЕМУ ПОСОХ).
